name: SÃ©rgio Kopplin
bio: 'Desenvolvedor Front-end na Catho'
picture: 'assets/images/profile.jpg'

url: http://koppl.in
permalink: /:title/

markdown: kramdown
highlighter: rouge

analytics: 'UA-74587546-1'
disqus: sergiokopplin
facebook: sergiokopplin
youtube: sergiokopplin
spotify: 1259926422
github: sergiokopplin
email: sergiokopplin@gmail.com
office: catho.com.br

# if you don't need pagination, comment the *paginate* configs below
# paginate: 5
# paginate_path: "blog/:num/"

# if you don't need projects, comment the *projects* configs below
projects: true

# if you don't need about or blog, comment them out below
about: true
blog: true

# do you want to show the "read time" of the posts?
read-time: true

# do you want to show the "tags" inside the posts?
show-tags: true

# related posts inside a post?
related: true

# do you want some animations?
animation: true

gems:
  - jemoji
  - jekyll-mentions
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-paginate

jekyll-mentions:
    base_url: https://github.com

exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, indigo-gh-pages.zip, Rakefile, screen-shot.png, travis.sh]
